Array.prototype.equals=function(a){if(!a||this.length!=a.length)return!1;for(var b=0,c=this.length;b<c;b++)if(this[b]instanceof Array&&a[b]instanceof Array){if(!this[b].equals(a[b]))return!1}else if(this[b]!=a[b])return!1;return!0};
var _run=0,dataSet={array:null,min:null,q1:null,med:null,q3:null,max:null,mean:null,mode:null,outliers:null,stdDev:null,zScores:null,length:null},arrOps={get arrA(){var a=document.getElementById("inp").value.split(",").map(Number).sort(function(a,c){return a-c});a.equals(dataSet.array)||(console.log("New data"),dataSet={array:null,min:null,q1:null,med:null,q3:null,max:null,mean:null,mode:null,outliers:null,stdDev:null,zScores:null,length:null},dataSet.array=a);return a},get out(){delete this.out;
return this.out=document.getElementById("res")},get mean(){if(null===dataSet.mean){console.log("Mean getter called");for(var a=arrOps.arrA,b=0,c=0;c<a.length;c++)b+=a[c];dataSet.mean=b/a.length;return b/a.length}return dataSet.mean},get mode(){if(null===dataSet.mode){console.log("Mode getter called");for(var a=arrOps.arrA,b=[],c=[],e=[],d=0;d<a.length;d++)-1===c.indexOf(a[d])?(b.push([a[d],1]),c.push(a[d])):b[c.indexOf(a[d])][1]++;b=b.sort(function(a,b){return b[1]-a[1]});a=!0;for(d=c=0;d<b.length;d++)if(b[d][1]>=
c&&(c=b[d][1],e.push(b[d][0])),d<b.length-1&&b[d][1]!=b[d+1][1]){a=!1;break}a&&(e=["No mode"]);return dataSet.mode=e}return dataSet.mode},get stdDev(){var a=arrOps.arrA;if(null!==dataSet.stdDev)return dataSet.stdDev;console.log("Std. dev. getter called");for(var b=arrOps.mean,c=0,e=0;e<a.length;e++)c+=Math.pow(a[e]-b,2);a=Math.sqrt(c/(a.length-1));return dataSet.stdDev=a},get zScore(){var a=arrOps.arrA;if(null!==dataSet.zScores)return dataSet.zScores;for(var b=[],c=this.mean,e=this.stdDev,d=0;d<a.length;d++){var f=
parseFloat(((a[d]-c)/e).toFixed(4));b.push(f)}return dataSet.zScores=b},median:function(a){console.log("Median getter called");var b=Math.floor(a.length/2);return 1==a.length%2?{ans:a[b],half:b,incl:!0}:{ans:(a[b-1]+a[b])/2,half:b,incl:!1}},get length(){var a=arrOps.arrA;return dataset.length?dataset.length:dataset.length=a.length}},stOps={bWdat:function(){var a=arrOps.arrA,b,c,e;null===dataSet.min?(b=a[0],dataSet.min=b):b=dataSet.min;null===dataSet.max?(c=a[a.length-1],dataSet.max=c):c=dataSet.max;
null===dataSet.med?(e=arrOps.median(a),dataSet.med=e):e=dataSet.med;var d=e.ans,f;null===dataSet.q1||null===dataSet.q3?(f=e.incl?a.slice(0,e.half+1):a.slice(0,e.half),a=a.slice(e.half,a.length+1),f=arrOps.median(f).ans,a=arrOps.median(a).ans,dataSet.q1=f,dataSet.q3=a):(f=dataSet.q1,a=dataSet.q3);output("p",ar2Str([b,f,d,a,c]),"array");_run++},outliers:function(){var a=arrOps.arrA,b;null===dataSet.med?(b=arrOps.median(a),dataSet.med=b):b=dataSet.med;var c,e=[];if(null===dataSet.outliers){null===dataSet.q1||
null===dataSet.q3?(c=b.incl?a.slice(0,b.half+1):a.slice(0,b.half),b=a.slice(b.half,a.length+1),c=arrOps.median(c).ans,b=arrOps.median(b).ans,dataSet.q1=c,dataSet.q3=b):(c=dataSet.q1,b=dataSet.q3);var d=1.5*(b-c);c-=d;b+=d;for(d=0;d<Math.ceil(a.length/4);d++)a[d]<c&&e.push(a[d]);for(c=a.length-1-Math.floor(a.length/4);c<a.length;c++)a[c]>b&&e.push(a[c]);0===e.length&&e.push("No outliers");dataSet.outliers=e}else e=dataSet.outliers;output("p",ar2Str(e),"array");_run++},meanMode:function(){output("p",
ar2Str([arrOps.mean,ar2Str(arrOps.mode)]),"array")},arrange:function(){output("p",ar2Str(arrOps.arrA),"array")},stdDev:function(){output("p",arrOps.stdDev,"number")},zScore:function(){output("p",ar2Str(arrOps.arrA),"array");output("p",ar2Str(arrOps.zScore),"array")},length:function(){output("p",arr2str(arrOps.length),"array")}},ar2Str=function(a){for(var b="[",c=0;c<a.length;c++)b=c<a.length-1?b+(a[c]+", "):b+a[c];return b+"]"},output=function(a,b,c){a=document.createElement(a);a.innerText=b;a.classList.add(c,
_run);arrOps.out.appendChild(a);scroller()},init=function(){console.log("Initiating");document.getElementById("btn").addEventListener("click",stOps.bWdat);document.getElementById("btn1").addEventListener("click",stOps.outliers);document.getElementById("btn2").addEventListener("click",stOps.meanMode);document.getElementById("btn3").addEventListener("click",stOps.arrange);document.getElementById("btn4").addEventListener("click",stOps.stdDev);document.getElementById("btn5").addEventListener("click",
stOps.zScore)};setTimeout(init,100);
